### ISSUE TITLE
Error: Version is missing, please add it and upload again

### ISSUE THREAD

**Issue by prin53** [testappio/github-action#1]
I am using this GitHub Action to upload my app to TestApp.io, but with the latest CLI update I started getting an upload error on Android platform:

```bash

-------------- Releasing for Android only --------------
======> Extracting the APK info...
======> [APP NAME] | [BUNDLE ID] v (741)
======> Preparing the release....
Error: Version is missing, please add it and upload again
```

GitHub Actions version is v5
CLI version is v1.0.4 (4)

**Comment by Massad** [comment]
Hey @prin53 

I can see that the last successful version was (733) using TA-CLI v1.0.3, can you please confirm if the APK contains `versionName`?

From the log above, the `versionName` is missing as it's supposed to be after the `v`

======> [APP NAME] | [BUNDLE ID] v[`versionName`] (versionCode)

In most cases, you can verify it in `build.gradle`
```
defaultConfig {
  ...
  versionCode 1
  versionName "1.0" <=== this one
  ...
}
```

**Comment by prin53** [comment]
Thank you, I had `versionName` missing. Now it works fine. 👍
